version: 2.1

jobs:
  test:
    parameters:
      database:
        type: string
      redmine:
        type: string
      ruby:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby >>
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: redmine
          POSTGRES_PASSWORD: supers3kretdonthacklel
      - image: circleci/mysql:8.0.23
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: redmineuser
          MYSQL_DATABASE: redmine
          MYSQL_PASSWORD: supers3kretdonthacklel
          MYSQL_ROOT_PASSWORD: supers3kretdonthacklel
    steps:
      - checkout
      - run: |
          set -ex

          git clone https://github.com/redmine/redmine.git --branch << parameters.redmine >> --depth 1 redmine
          ln -s $PWD $PWD/redmine/plugins/redmine_tags
          cp config/database-<< parameters.database >>-test.yml redmine/config/database.yml
      - restore_cache:
          keys:
            - redmine-<< parameters.database >>-<< parameters.redmine >>-<< parameters.ruby >>
      - run: |
          set -ex

          cd redmine
          bundle config jobs 4
          bundle config retry 3
          bundle config path vendor/bundle
          bundle install
      - save_cache:
          key: redmine-<< parameters.database >>-<< parameters.redmine >>-<< parameters.ruby >>
          paths:
            - redmine/vendor/bundle
      - run: |
          set -ex

          cd redmine
          mv plugins/redmine_tags .
          bundle exec rake db:create db:migrate

          mv redmine_tags plugins/
          bundle exec rake redmine:plugins:migrate NAME=redmine_tags

          bundle exec rake redmine:plugins:test NAME=redmine_tags

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              database: ['mysql', 'postgres']
              redmine: ['4.2.0', '4.2-stable', '4.1.2', '4.1-stable']
              ruby: ['2.7.3', '2.6.7', '2.5.9']
            exclude:
              - database: 'mysql'
                redmine: '4.1.2'
                ruby: '2.7.3'
              - database: 'mysql'
                redmine: '4.1-stable'
                ruby: '2.7.3'
              - database: 'postgres'
                redmine: '4.1.2'
                ruby: '2.7.3'
              - database: 'postgres'
                redmine: '4.1-stable'
                ruby: '2.7.3'
